# Generated by Django 4.2 on 2023-04-23 17:45

import cards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_remove_cardmodel_imglink_cardmodel_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("image", models.FileField(upload_to=cards.models.get_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="file",
            field=models.FileField(upload_to=cards.models.get_file_path),
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="image",
            field=models.FileField(upload_to=cards.models.get_image_path),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cards.categorymodel",
            ),
            preserve_default=False,
        ),
    ]
