# Generated by Django 4.2 on 2023-04-24 18:14

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_categorymodel_alter_cardmodel_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to=cards.models.get_image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name="cardmodel",
            name="image",
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="images",
            field=models.ManyToManyField(to="cards.cardimage"),
        ),
    ]
