# Generated by Django 4.2 on 2023-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_cardimage_remove_cardmodel_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
