# Generated by Django 4.2 on 2023-06-04 14:56

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_cardmodel_category_type_cardmodel_isnews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardmodel",
            name="isNews",
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="category_type",
            field=models.CharField(
                choices=[("NW", "News"), ("BK", "Books")], default="BK", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=cards.models.get_file_path
            ),
        ),
    ]
