# Generated by Django 4.2 on 2023-06-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_remove_cardmodel_isnews_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardmodel",
            name="video_link",
        ),
        migrations.AddField(
            model_name="cardimage",
            name="isVideo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardimage",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="isPreview",
            field=models.BooleanField(default=True),
        ),
    ]
