# Generated by Django 4.2 on 2023-06-14 02:36

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_remove_cardmodel_video_link_cardimage_isvideo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardimage",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=cards.models.get_image_path
            ),
        ),
    ]
